/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apprestaurante.Vista.viewAdmin;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carlo
 */
public class viewMainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form viewMainAdmin
     */
    public viewMainAdmin() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/picture/Exit.png"));
        Image imagen1 = icono1.getImage().getScaledInstance(
            lExit.getWidth(),
            lExit.getHeight(),
            Image.SCALE_SMOOTH
        );
        lExit.setIcon(new ImageIcon(imagen1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewMain = new javax.swing.JPanel();
        mainStatistics = new javax.swing.JPanel();
        tableManagement = new javax.swing.JPanel();
        waiterManagement = new javax.swing.JPanel();
        dishManagement = new javax.swing.JPanel();
        orderManagement = new javax.swing.JPanel();
        viewTop = new javax.swing.JPanel();
        lExit = new javax.swing.JLabel();
        viewMenu = new javax.swing.JPanel();
        buttonMain = new javax.swing.JButton();
        buttonTable = new javax.swing.JButton();
        buttonWaiter = new javax.swing.JButton();
        buttonDish = new javax.swing.JButton();
        buttonOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewMain.setBackground(new java.awt.Color(255, 255, 255));
        viewMain.setLayout(new java.awt.CardLayout());

        mainStatistics.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainStatisticsLayout = new javax.swing.GroupLayout(mainStatistics);
        mainStatistics.setLayout(mainStatisticsLayout);
        mainStatisticsLayout.setHorizontalGroup(
            mainStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        mainStatisticsLayout.setVerticalGroup(
            mainStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        viewMain.add(mainStatistics, "mainStatistics");

        tableManagement.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tableManagementLayout = new javax.swing.GroupLayout(tableManagement);
        tableManagement.setLayout(tableManagementLayout);
        tableManagementLayout.setHorizontalGroup(
            tableManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        tableManagementLayout.setVerticalGroup(
            tableManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        viewMain.add(tableManagement, "tableManagement");

        waiterManagement.setBackground(new java.awt.Color(153, 255, 0));

        javax.swing.GroupLayout waiterManagementLayout = new javax.swing.GroupLayout(waiterManagement);
        waiterManagement.setLayout(waiterManagementLayout);
        waiterManagementLayout.setHorizontalGroup(
            waiterManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        waiterManagementLayout.setVerticalGroup(
            waiterManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        viewMain.add(waiterManagement, "waiterManagement");

        dishManagement.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout dishManagementLayout = new javax.swing.GroupLayout(dishManagement);
        dishManagement.setLayout(dishManagementLayout);
        dishManagementLayout.setHorizontalGroup(
            dishManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        dishManagementLayout.setVerticalGroup(
            dishManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        viewMain.add(dishManagement, "dishManagement");

        orderManagement.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout orderManagementLayout = new javax.swing.GroupLayout(orderManagement);
        orderManagement.setLayout(orderManagementLayout);
        orderManagementLayout.setHorizontalGroup(
            orderManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        orderManagementLayout.setVerticalGroup(
            orderManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        viewMain.add(orderManagement, "orderManagement");

        getContentPane().add(viewMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 660, 440));

        viewTop.setBackground(new java.awt.Color(0, 141, 155));

        lExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewTopLayout = new javax.swing.GroupLayout(viewTop);
        viewTop.setLayout(viewTopLayout);
        viewTopLayout.setHorizontalGroup(
            viewTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTopLayout.createSequentialGroup()
                .addContainerGap(737, Short.MAX_VALUE)
                .addComponent(lExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        viewTopLayout.setVerticalGroup(
            viewTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(viewTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        viewMenu.setBackground(new java.awt.Color(204, 204, 204));

        buttonMain.setBackground(new java.awt.Color(204, 204, 204));
        buttonMain.setForeground(new java.awt.Color(255, 255, 255));
        buttonMain.setText("Principal");
        buttonMain.setBorder(null);
        buttonMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMainMouseClicked(evt);
            }
        });

        buttonTable.setBackground(new java.awt.Color(204, 204, 204));
        buttonTable.setForeground(new java.awt.Color(255, 255, 255));
        buttonTable.setText("Mesas");
        buttonTable.setBorder(null);
        buttonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTableMouseClicked(evt);
            }
        });

        buttonWaiter.setBackground(new java.awt.Color(204, 204, 204));
        buttonWaiter.setForeground(new java.awt.Color(255, 255, 255));
        buttonWaiter.setText("Meseros");
        buttonWaiter.setBorder(null);
        buttonWaiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonWaiterMouseClicked(evt);
            }
        });

        buttonDish.setBackground(new java.awt.Color(204, 204, 204));
        buttonDish.setForeground(new java.awt.Color(255, 255, 255));
        buttonDish.setText("Platos");
        buttonDish.setBorder(null);
        buttonDish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDishMouseClicked(evt);
            }
        });

        buttonOrder.setBackground(new java.awt.Color(204, 204, 204));
        buttonOrder.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrder.setText("Pedidos");
        buttonOrder.setBorder(null);
        buttonOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewMenuLayout = new javax.swing.GroupLayout(viewMenu);
        viewMenu.setLayout(viewMenuLayout);
        viewMenuLayout.setHorizontalGroup(
            viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addGroup(viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(viewMenuLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(buttonWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, viewMenuLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonTable, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(buttonDish, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        viewMenuLayout.setVerticalGroup(
            viewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(buttonMain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonTable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttonDish, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(buttonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(viewMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMainMouseClicked
        CardLayout cl = (CardLayout) viewMain.getLayout();
        cl.show(viewMain, "mainStatistics");
    }//GEN-LAST:event_buttonMainMouseClicked

    private void buttonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTableMouseClicked
        CardLayout cl = (CardLayout) viewMain.getLayout();
        cl.show(viewMain, "tableManagement");
    }//GEN-LAST:event_buttonTableMouseClicked

    private void buttonWaiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonWaiterMouseClicked
        CardLayout cl = (CardLayout) viewMain.getLayout();
        cl.show(viewMain, "waiterManagement");
    }//GEN-LAST:event_buttonWaiterMouseClicked

    private void buttonDishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDishMouseClicked
        CardLayout cl = (CardLayout) viewMain.getLayout();
        cl.show(viewMain, "dishManagement");
    }//GEN-LAST:event_buttonDishMouseClicked

    private void buttonOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOrderMouseClicked
        CardLayout cl = (CardLayout) viewMain.getLayout();
        cl.show(viewMain, "orderManagement");
    }//GEN-LAST:event_buttonOrderMouseClicked

    private void lExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExitMouseClicked
        System.exit(0); 
    }//GEN-LAST:event_lExitMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new viewMainAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDish;
    private javax.swing.JButton buttonMain;
    private javax.swing.JButton buttonOrder;
    private javax.swing.JButton buttonTable;
    private javax.swing.JButton buttonWaiter;
    private javax.swing.JPanel dishManagement;
    private javax.swing.JLabel lExit;
    private javax.swing.JPanel mainStatistics;
    private javax.swing.JPanel orderManagement;
    private javax.swing.JPanel tableManagement;
    private javax.swing.JPanel viewMain;
    private javax.swing.JPanel viewMenu;
    private javax.swing.JPanel viewTop;
    private javax.swing.JPanel waiterManagement;
    // End of variables declaration//GEN-END:variables
}
