/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apprestaurante.Vista.viewWaiter;

import com.mycompany.apprestaurante.Vista.viewAdmin.tableForm;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author carlo
 */
public class viewMainWaiter extends javax.swing.JFrame {

    /**
     * Creates new form viewMainAdmin
     */
    
    /**
     * labelCurrentOccupation= porcentaje de ocupacion    
     * 
     */    
    
    public viewMainWaiter() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/picture/Exit1.png"));
        Image imagen1 = icono1.getImage().getScaledInstance(lExit1.getWidth(),lExit1.getHeight(),Image.SCALE_SMOOTH);
        lExit1.setIcon(new ImageIcon(imagen1));
        ImageIcon icono2 = new ImageIcon(getClass().getResource("/picture/pedido.png"));
        Image imagen2 = icono2.getImage().getScaledInstance(lPedido.getWidth(),lPedido.getHeight(),Image.SCALE_SMOOTH);
        lPedido.setIcon(new ImageIcon(imagen2));
        ImageIcon icono3 = new ImageIcon(getClass().getResource("/picture/items.png"));
        Image imagen3 = icono3.getImage().getScaledInstance(lItems.getWidth(),lItems.getHeight(),Image.SCALE_SMOOTH);
        lItems.setIcon(new ImageIcon(imagen3));
        ImageIcon icono4 = new ImageIcon(getClass().getResource("/picture/princi.png"));
        Image imagen4 = icono4.getImage().getScaledInstance(20,20,Image.SCALE_SMOOTH);
        lPrinci.setIcon(new ImageIcon(imagen4));
        ImageIcon icono5 = new ImageIcon(getClass().getResource("/picture/pedido1.png"));
        Image imagen5 = icono5.getImage().getScaledInstance(40,40,Image.SCALE_SMOOTH);
        lpedido.setIcon(new ImageIcon(imagen5));
        ImageIcon icono6 = new ImageIcon(getClass().getResource("/picture/item.png"));
        Image imagen6 = icono6.getImage().getScaledInstance(20,20,Image.SCALE_SMOOTH);
        lmisPedidos.setIcon(new ImageIcon(imagen6));
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lPedido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lItems = new javax.swing.JLabel();
        viewTop = new javax.swing.JPanel();
        lExit1 = new javax.swing.JLabel();
        viewMenu = new javax.swing.JPanel();
        buttonTable = new javax.swing.JButton();
        buttonMain = new javax.swing.JButton();
        buttonWaiter = new javax.swing.JButton();
        buttonOrder = new javax.swing.JButton();
        lPrinci = new javax.swing.JLabel();
        lpedido = new javax.swing.JLabel();
        lmisPedidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido, Paco");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Tu panel de control para gestionar eficientemente tus tareas diarias");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tomar Pedido");

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("<html><div style='text-align:center;'>Inicia un nuevo pedido para gestionar<br> eficientemente tus tareas diarias</div></html>");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mis Pedidos");

        jButton1.setBackground(new java.awt.Color(0, 141, 155));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tomar Pedido");

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("<html><div style='text-align:center;'>Revisa y gestiona el<br>estado de tus pedidos activos</div></html>");

        jButton2.setBackground(new java.awt.Color(0, 141, 155));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mis Pedidos");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(159, 159, 159))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addGap(75, 75, 75))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lItems, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelPrincipal, "principal");

        getContentPane().add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 670, 440));

        viewTop.setBackground(new java.awt.Color(0, 141, 155));

        lExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewTopLayout = new javax.swing.GroupLayout(viewTop);
        viewTop.setLayout(viewTopLayout);
        viewTopLayout.setHorizontalGroup(
            viewTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTopLayout.createSequentialGroup()
                .addContainerGap(774, Short.MAX_VALUE)
                .addComponent(lExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        viewTopLayout.setVerticalGroup(
            viewTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(viewTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        viewMenu.setBackground(new java.awt.Color(204, 204, 204));
        viewMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonTable.setBackground(new java.awt.Color(204, 204, 204));
        buttonTable.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        buttonTable.setForeground(new java.awt.Color(0, 0, 0));
        buttonTable.setText("Tomar Pedido");
        buttonTable.setBorder(null);
        buttonTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTableMouseClicked(evt);
            }
        });
        viewMenu.add(buttonTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 83, 96, 28));

        buttonMain.setBackground(new java.awt.Color(204, 204, 204));
        buttonMain.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        buttonMain.setForeground(new java.awt.Color(0, 0, 0));
        buttonMain.setText("Principal");
        buttonMain.setBorder(null);
        buttonMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMainMouseClicked(evt);
            }
        });
        buttonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainActionPerformed(evt);
            }
        });
        viewMenu.add(buttonMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 28));

        buttonWaiter.setBackground(new java.awt.Color(204, 204, 204));
        buttonWaiter.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        buttonWaiter.setForeground(new java.awt.Color(0, 0, 0));
        buttonWaiter.setText("Mis Pedidos");
        buttonWaiter.setBorder(null);
        buttonWaiter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonWaiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonWaiterMouseClicked(evt);
            }
        });
        buttonWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWaiterActionPerformed(evt);
            }
        });
        viewMenu.add(buttonWaiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 117, 96, 28));

        buttonOrder.setBackground(new java.awt.Color(204, 204, 204));
        buttonOrder.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        buttonOrder.setForeground(new java.awt.Color(0, 0, 0));
        buttonOrder.setText("Cerrar");
        buttonOrder.setBorder(null);
        buttonOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOrderMouseClicked(evt);
            }
        });
        viewMenu.add(buttonOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 406, 78, 28));

        lPrinci.setBackground(new java.awt.Color(204, 204, 204));
        lPrinci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPrinci.setOpaque(true);
        viewMenu.add(lPrinci, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 34, 28));

        lpedido.setBackground(new java.awt.Color(204, 204, 204));
        lpedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpedido.setOpaque(true);
        viewMenu.add(lpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 34, 28));

        lmisPedidos.setBackground(new java.awt.Color(204, 204, 204));
        lmisPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmisPedidos.setOpaque(true);
        viewMenu.add(lmisPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 34, 28));

        getContentPane().add(viewMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMainMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "mainStatistics");
    }//GEN-LAST:event_buttonMainMouseClicked

    private void buttonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTableMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "tableManagement");
    }//GEN-LAST:event_buttonTableMouseClicked

    private void buttonWaiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonWaiterMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "waiterManagement");
    }//GEN-LAST:event_buttonWaiterMouseClicked

    private void buttonOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOrderMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "orderManagement");
    }//GEN-LAST:event_buttonOrderMouseClicked

    private void lExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExit1MouseClicked
        System.exit(0); 
    }//GEN-LAST:event_lExit1MouseClicked

    private void buttonWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWaiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonWaiterActionPerformed

    private void buttonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "principal");
    }//GEN-LAST:event_buttonMainActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new viewMainAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton buttonMain;
    private javax.swing.JButton buttonOrder;
    private javax.swing.JButton buttonTable;
    private javax.swing.JButton buttonWaiter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lExit1;
    private javax.swing.JLabel lItems;
    private javax.swing.JLabel lPedido;
    private javax.swing.JLabel lPrinci;
    private javax.swing.JLabel lmisPedidos;
    private javax.swing.JLabel lpedido;
    private javax.swing.JPanel viewMenu;
    private javax.swing.JPanel viewTop;
    // End of variables declaration//GEN-END:variables
}
