/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apprestaurante.Vista.viewWaiter;




import com.mycompany.apprestaurante.Controlador.orderController.OrderController;
import com.mycompany.apprestaurante.Controlador.orderDishController.OrderDishController;
import com.mycompany.apprestaurante.Controlador.tableController.TableController;
import com.mycompany.apprestaurante.Controlador.waiterController.WaiterController;
import com.mycompany.apprestaurante.Modelo.dto.orderTableDTO;
import com.mycompany.apprestaurante.Modelo.entities.Dish;
import com.mycompany.apprestaurante.Modelo.entities.Table;
import com.mycompany.apprestaurante.Vista.viewAdmin.tableForm;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author carlo
 */
public class viewMainWaiter extends javax.swing.JFrame {
    
   private int idWaiter;
   private int idTable;
   private OrderController orderController = new OrderController();
   private WaiterController waiterController = new WaiterController();
   private OrderDishController orderDishController = new OrderDishController();
   private TableController tableController = new TableController();
    
    public viewMainWaiter(String name) {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/picture/Exit1.png"));
        Image imagen1 = icono1.getImage().getScaledInstance(lExit1.getWidth(),lExit1.getHeight(),Image.SCALE_SMOOTH);
        lExit1.setIcon(new ImageIcon(imagen1));
        ImageIcon icono2 = new ImageIcon(getClass().getResource("/picture/pedido.png"));
        Image imagen2 = icono2.getImage().getScaledInstance(lPedido.getWidth(),lPedido.getHeight(),Image.SCALE_SMOOTH);
        lPedido.setIcon(new ImageIcon(imagen2));
        ImageIcon icono3 = new ImageIcon(getClass().getResource("/picture/items.png"));
        Image imagen3 = icono3.getImage().getScaledInstance(lItems.getWidth(),lItems.getHeight(),Image.SCALE_SMOOTH);
        lItems.setIcon(new ImageIcon(imagen3));
        ImageIcon icono4 = new ImageIcon(getClass().getResource("/picture/princi.png"));
        Image imagen4 = icono4.getImage().getScaledInstance(20,20,Image.SCALE_SMOOTH);
        lMain.setIcon(new ImageIcon(imagen4));
        ImageIcon icono5 = new ImageIcon(getClass().getResource("/picture/pedido1.png"));
        Image imagen5 = icono5.getImage().getScaledInstance(40,40,Image.SCALE_SMOOTH);
        lOrder.setIcon(new ImageIcon(imagen5));
        ImageIcon icono6 = new ImageIcon(getClass().getResource("/picture/item.png"));
        Image imagen6 = icono6.getImage().getScaledInstance(20,20,Image.SCALE_SMOOTH);
        lMyOrder.setIcon(new ImageIcon(imagen6));
        ImageIcon icono7 = new ImageIcon(getClass().getResource("/picture/CerSesion.png"));
        Image imagen7 = icono7.getImage().getScaledInstance(20,20,Image.SCALE_SMOOTH);
        botonExit.setIcon(new ImageIcon(imagen7));
        ImageIcon icono8 = new ImageIcon(getClass().getResource("/picture/cubierto.png"));
        Image imagen8 = icono8.getImage().getScaledInstance(20,20,Image.SCALE_SMOOTH);
        ldetalle.setIcon(new ImageIcon(imagen8));
        
        this.idWaiter = waiterController.findByName(name);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PanelContenedor = new javax.swing.JPanel();
        PanelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lPedido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lItems = new javax.swing.JLabel();
        PanelOrder = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        PanelMyOrder = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOrder1 = new javax.swing.JTable();
        ldetalle = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        viewTop = new javax.swing.JPanel();
        lExit1 = new javax.swing.JLabel();
        viewMenu = new javax.swing.JPanel();
        botonOrder = new javax.swing.JButton();
        botonMain = new javax.swing.JButton();
        botonMyOrder = new javax.swing.JButton();
        botonExit = new javax.swing.JButton();
        lMain = new javax.swing.JLabel();
        lOrder = new javax.swing.JLabel();
        lMyOrder = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido, Paco");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Tu panel de control para gestionar eficientemente tus tareas diarias");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tomar Pedido");

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("<html><div style='text-align:center;'>Inicia un nuevo pedido para gestionar<br> eficientemente tus tareas diarias</div></html>");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mis Pedidos");

        jButton1.setBackground(new java.awt.Color(0, 141, 155));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tomar Pedido");

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("<html><div style='text-align:center;'>Revisa y gestiona el<br>estado de tus pedidos activos</div></html>");

        jButton2.setBackground(new java.awt.Color(0, 141, 155));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mis Pedidos");

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(159, 159, 159))
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(PanelMainLayout.createSequentialGroup()
                                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelMainLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelMainLayout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addGap(75, 75, 75))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lItems, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelMain, "principal");

        PanelOrder.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Seleccione la Mesa");

        javax.swing.GroupLayout PanelOrderLayout = new javax.swing.GroupLayout(PanelOrder);
        PanelOrder.setLayout(PanelOrderLayout);
        PanelOrderLayout.setHorizontalGroup(
            PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrderLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        PanelOrderLayout.setVerticalGroup(
            PanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelOrder, "card3");

        PanelMyOrder.setBackground(new java.awt.Color(255, 255, 255));
        PanelMyOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Informacion del Pedido");
        PanelMyOrder.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 14, -1, -1));

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOrder);

        PanelMyOrder.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 58, 410, 346));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("No hay platos en el Pedido");
        PanelMyOrder.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        tableOrder1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(tableOrder1);

        PanelMyOrder.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 58, 168, 261));

        ldetalle.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        ldetalle.setForeground(new java.awt.Color(0, 0, 0));
        ldetalle.setText("Detalle del Pedido");
        PanelMyOrder.add(ldetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 141, 155));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Pagar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelMyOrder.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 368, 152, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total:");
        PanelMyOrder.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 327, -1, -1));

        lTotal.setBackground(new java.awt.Color(0, 141, 155));
        lTotal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lTotal.setText("$   0");
        PanelMyOrder.add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 90, -1));

        PanelContenedor.add(PanelMyOrder, "card4");

        getContentPane().add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 670, 440));

        viewTop.setBackground(new java.awt.Color(0, 141, 155));

        lExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewTopLayout = new javax.swing.GroupLayout(viewTop);
        viewTop.setLayout(viewTopLayout);
        viewTopLayout.setHorizontalGroup(
            viewTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTopLayout.createSequentialGroup()
                .addContainerGap(774, Short.MAX_VALUE)
                .addComponent(lExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        viewTopLayout.setVerticalGroup(
            viewTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(viewTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        viewMenu.setBackground(new java.awt.Color(204, 204, 204));
        viewMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonOrder.setBackground(new java.awt.Color(204, 204, 204));
        botonOrder.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        botonOrder.setForeground(new java.awt.Color(0, 0, 0));
        botonOrder.setText("Tomar Pedido");
        botonOrder.setBorder(null);
        botonOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonOrderMouseExited(evt);
            }
        });
        viewMenu.add(botonOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 36, 96, 28));

        botonMain.setBackground(new java.awt.Color(204, 204, 204));
        botonMain.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        botonMain.setForeground(new java.awt.Color(0, 0, 0));
        botonMain.setText("Principal");
        botonMain.setBorder(null);
        botonMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMainMouseExited(evt);
            }
        });
        botonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMainActionPerformed(evt);
            }
        });
        viewMenu.add(botonMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 3, 96, 28));

        botonMyOrder.setBackground(new java.awt.Color(204, 204, 204));
        botonMyOrder.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        botonMyOrder.setForeground(new java.awt.Color(0, 0, 0));
        botonMyOrder.setText("Mis Pedidos");
        botonMyOrder.setBorder(null);
        botonMyOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonMyOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMyOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMyOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMyOrderMouseExited(evt);
            }
        });
        botonMyOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMyOrderActionPerformed(evt);
            }
        });
        viewMenu.add(botonMyOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 72, 96, 28));

        botonExit.setBackground(new java.awt.Color(204, 204, 204));
        botonExit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        botonExit.setForeground(new java.awt.Color(0, 0, 0));
        botonExit.setText("Cerrar");
        botonExit.setBorder(null);
        botonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonExitMouseExited(evt);
            }
        });
        viewMenu.add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 413, 130, 28));

        lMain.setBackground(new java.awt.Color(204, 204, 204));
        lMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMain.setOpaque(true);
        lMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lMainMouseExited(evt);
            }
        });
        viewMenu.add(lMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 34, 28));

        lOrder.setBackground(new java.awt.Color(204, 204, 204));
        lOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lOrder.setOpaque(true);
        lOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lOrderMouseExited(evt);
            }
        });
        viewMenu.add(lOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 34, 28));

        lMyOrder.setBackground(new java.awt.Color(204, 204, 204));
        lMyOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMyOrder.setOpaque(true);
        lMyOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lMyOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lMyOrderMouseExited(evt);
            }
        });
        viewMenu.add(lMyOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 34, 28));

        getContentPane().add(viewMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMainMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "mainStatistics");
    }//GEN-LAST:event_botonMainMouseClicked

    private void botonOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOrderMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "tableManagement");
    }//GEN-LAST:event_botonOrderMouseClicked

    private void botonMyOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMyOrderMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "waiterManagement");
    }//GEN-LAST:event_botonMyOrderMouseClicked

    private void botonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseClicked
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "orderManagement");
    }//GEN-LAST:event_botonExitMouseClicked

    private void lExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExit1MouseClicked
        System.exit(0); 
    }//GEN-LAST:event_lExit1MouseClicked

    private void botonMyOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMyOrderActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "card4");
        loadTableOrder();
    }//GEN-LAST:event_botonMyOrderActionPerformed

    private void botonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMainActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "principal");
    }//GEN-LAST:event_botonMainActionPerformed

    private void lMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMainMouseEntered
        // TODO add your handling code here:
        lMain.setBackground(Color.decode("#008D9B"));
        botonMain.setBackground(Color.decode("#008D9B"));
    }//GEN-LAST:event_lMainMouseEntered

    private void lMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMainMouseExited
        // TODO add your handling code here:
        lMain.setBackground(Color.decode("#CCCCCC"));
        botonMain.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_lMainMouseExited

    private void lOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lOrderMouseClicked
        // TODO add your handling code here:
        botonOrder.doClick();
    }//GEN-LAST:event_lOrderMouseClicked

    private void lOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lOrderMouseEntered
        // TODO add your handling code here:
        lOrder.setBackground(Color.decode("#008D9B"));
        botonOrder.setBackground(Color.decode("#008D9B"));
    }//GEN-LAST:event_lOrderMouseEntered

    private void lOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lOrderMouseExited
        // TODO add your handling code here:
        lOrder.setBackground(Color.decode("#CCCCCC"));
        botonOrder.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_lOrderMouseExited

    private void lMyOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMyOrderMouseEntered
        // TODO add your handling code here:
        lMyOrder.setBackground(Color.decode("#008D9B"));
        botonMyOrder.setBackground(Color.decode("#008D9B"));
    }//GEN-LAST:event_lMyOrderMouseEntered

    private void lMyOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMyOrderMouseExited
        // TODO add your handling code here:
        lMyOrder.setBackground(Color.decode("#CCCCCC"));
        botonMyOrder.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_lMyOrderMouseExited

    private void botonMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMainMouseEntered
        // TODO add your handling code here:
        lMain.setBackground(Color.decode("#008D9B"));
        botonMain.setBackground(Color.decode("#008D9B"));
    }//GEN-LAST:event_botonMainMouseEntered

    private void botonMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMainMouseExited
        // TODO add your handling code here:
         lMain.setBackground(Color.decode("#CCCCCC"));
        botonMain.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_botonMainMouseExited

    private void botonOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOrderMouseEntered
        // TODO add your handling code here:
        lOrder.setBackground(Color.decode("#008D9B"));
        botonOrder.setBackground(Color.decode("#008D9B"));
    }//GEN-LAST:event_botonOrderMouseEntered

    private void botonOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOrderMouseExited
        // TODO add your handling code here:
        lOrder.setBackground(Color.decode("#CCCCCC"));
        botonOrder.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_botonOrderMouseExited

    private void botonMyOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMyOrderMouseEntered
        // TODO add your handling code here:
        lMyOrder.setBackground(Color.decode("#008D9B"));
        botonMyOrder.setBackground(Color.decode("#008D9B"));
    }//GEN-LAST:event_botonMyOrderMouseEntered

    private void botonMyOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMyOrderMouseExited
        // TODO add your handling code here:
        lMyOrder.setBackground(Color.decode("#CCCCCC"));
        botonMyOrder.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_botonMyOrderMouseExited

    private void botonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseEntered
        // TODO add your handling code here:
        botonExit.setBackground(Color.decode("#FF6666"));
        botonExit.setForeground(Color.white);
    }//GEN-LAST:event_botonExitMouseEntered

    private void botonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseExited
        // TODO add your handling code here:
        botonExit.setBackground(Color.decode("#CCCCCC"));
        botonExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonExitMouseExited

    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        // TODO add your handling code here:
        int fila = tableOrder.getSelectedRow();
        String state = tableOrder.getValueAt(fila,2).toString();
        if(state.equals("Activo")) {
            int idOrder = Integer.parseInt(tableOrder.getValueAt(fila, 0).toString());
            lTotal.setText("$   " + tableOrder.getValueAt(fila, 3).toString());
            loadTableOrderClick(idOrder);
            this.idTable = Integer.parseInt(tableOrder.getValueAt(fila, 1).toString());
            jLabel10.setVisible(false);
        }else{
            jLabel10.setVisible(true);
        }
    }//GEN-LAST:event_tableOrderMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(this.idTable != 0){
            tableController.modifyTable(this.idTable);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un Pedido a Pagar!!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void loadTableOrder(){
        List<orderTableDTO> lista = orderController.findByIdWaiter(idWaiter);
        String[] columnas = {"Numero","Mesa","Estado","Total"};
        DefaultTableModel tabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (orderTableDTO order : lista) {
            String state = "Inactivo";
            if(order.isState())state = "Activo";
            Object[] filas = {
                    order.getIdOrder(),
                    order.getIdTable(),
                    state,
                    order.getTotal()
            };
            tabla.addRow(filas);
        }
        tableOrder.setModel(tabla);
        applyTableStyle(tableOrder);
    }
    
    private void loadTableOrderClick(int idOrder){
        List<Dish> lista = orderDishController.findByIdOrder(idOrder);
        String[] columnas = {"Nombre"};
        DefaultTableModel tabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (Dish dish : lista) {
            Object[] filas = {
                    dish.getNombre()
            };
            tabla.addRow(filas);
        }
        tableOrder1.setModel(tabla);
        applyTableStyle(tableOrder1);
    }

    private void loadTable(){
        List<Table> lista = tableController.listTable();
        String[] columnas = {"Numero","Capacidad","Disponiible"};
        DefaultTableModel tabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (Table table : lista) {
            Object[] filas = {
                    table.getId(),
                    table.getCapacity(),
                    table.getState()
            };
            tabla.addRow(filas);
        }
        tableOrder1.setModel(tabla);
        applyTableStyle(tableOrder1);
    }
    public void applyTableStyle(JTable tabla) {

        JTableHeader header = tabla.getTableHeader();
        header.setOpaque(false);
        header.setBackground(Color.decode("#008D9B"));
        header.setForeground(Color.WHITE);
        header.setFont(new Font("Yu Gothic UI Semilight", Font.BOLD, 14));

        tabla.setShowGrid(false);
        tabla.setIntercellSpacing(new Dimension(0, 0));

        tabla.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                Color par = Color.WHITE;
                Color impar = Color.decode("#CCCCCC");

                if (!isSelected) {
                    c.setBackground(row % 2 == 0 ? par : impar);
                    c.setForeground(Color.BLACK);
                } else {
                    c.setBackground(new Color(0, 120, 215));
                    c.setForeground(Color.WHITE);
                }

                return c;
            }
        });
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(viewMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new viewMainAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelMyOrder;
    private javax.swing.JPanel PanelOrder;
    private javax.swing.JButton botonExit;
    private javax.swing.JButton botonMain;
    private javax.swing.JButton botonMyOrder;
    private javax.swing.JButton botonOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lExit1;
    private javax.swing.JLabel lItems;
    private javax.swing.JLabel lMain;
    private javax.swing.JLabel lMyOrder;
    private javax.swing.JLabel lOrder;
    private javax.swing.JLabel lPedido;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel ldetalle;
    private javax.swing.JTable tableOrder;
    private javax.swing.JTable tableOrder1;
    private javax.swing.JPanel viewMenu;
    private javax.swing.JPanel viewTop;
    // End of variables declaration//GEN-END:variables
}
