/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apprestaurante.Vista.Login;


import com.mycompany.apprestaurante.Controlador.userController.UserController;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author carde
 */
public class login extends javax.swing.JFrame {
    
    private UserController usController = new UserController();
     private int x = 0;
    /**
     * Creates new form login
     */
    public login() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/picture/Exit.png"));
        Image imagen1 = icono1.getImage().getScaledInstance(
            lExit.getWidth(),
            lExit.getHeight(),
            Image.SCALE_SMOOTH
        );
        lExit.setIcon(new ImageIcon(imagen1));
        ImageIcon icono3 = new ImageIcon(getClass().getResource("/picture/flecha.png"));
        Image imagen3 = icono3.getImage().getScaledInstance(
            lAtras.getWidth(),
            lAtras.getHeight(),
            Image.SCALE_SMOOTH
        );
        lAtras.setIcon(new ImageIcon(imagen3));
        ImageIcon icono2 = new ImageIcon(getClass().getResource("/picture/ver.png"));
        Image imagen2 = icono2.getImage().getScaledInstance(
                icVer.getWidth(),
                icVer.getHeight(),
                Image.SCALE_SMOOTH
        );
        icVer.setIcon(new ImageIcon(imagen2));
        
        cajaPassword.setEchoChar((char) 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cajaPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cajaUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icVer = new javax.swing.JLabel();
        lExit = new javax.swing.JLabel();
        lAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jButton1.setBackground(new java.awt.Color(0, 141, 155));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cajaPassword.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        cajaPassword.setForeground(java.awt.Color.gray);
        cajaPassword.setText("Ingrese Contraseña");
        cajaPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajaPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaPasswordFocusLost(evt);
            }
        });
        cajaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPasswordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña");

        cajaUser.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 10)); // NOI18N
        cajaUser.setForeground(java.awt.Color.gray);
        cajaUser.setText("Ingrese Usuario");
        cajaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajaUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaUserFocusLost(evt);
            }
        });
        cajaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Inicia sesión para acceder a tu cuenta.");

        labelLogo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 28)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(0, 0, 0));
        labelLogo.setText("Acceso de Administrador");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sabores del Fogon");

        icVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cajaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(cajaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51)))
                .addGap(18, 18, 18)
                .addComponent(icVer, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelLogo)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(cajaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icVer, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(84, 84, 84))
        );

        lExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExitMouseClicked(evt);
            }
        });

        lAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lExit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lExit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String nameUser = cajaUser.getText();
            String password = cajaPassword.getText();
            boolean hide = usController.validateLogin(nameUser, password);
            if(hide){
                this.setVisible(false);
            }
        }catch(Exception e){
            System.out.println("Error al convertir datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cajaUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaUserFocusGained
        // TODO add your handling code here:
        if (cajaUser.getText().equals("Ingrese Usuario")) {
            cajaUser.setText("");
            cajaUser.setForeground(Color.black);
            cajaUser.setFont(new Font("Sitka Text", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_cajaUserFocusGained

    private void cajaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaPasswordActionPerformed

    private void cajaPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaPasswordFocusGained
        // TODO add your handling code here:
         if (cajaPassword.getText().equals("Ingrese Contraseña")) {
            cajaPassword.setEchoChar('●');
            cajaPassword.setText("");
            cajaPassword.setForeground(Color.black);
            cajaPassword.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        }
        
    }//GEN-LAST:event_cajaPasswordFocusGained

    private void cajaPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaPasswordFocusLost
        // TODO add your handling code here:
        if (cajaPassword.getText().isEmpty()) {
            cajaPassword.setEchoChar((char) 0);
            cajaPassword.setText("Ingrese Contraseña");
            cajaPassword.setForeground(Color.gray);
            cajaPassword.setFont(new Font("Segoe UI", Font.PLAIN, 10));
        }
    }//GEN-LAST:event_cajaPasswordFocusLost

    private void cajaUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaUserFocusLost
        // TODO add your handling code here:
       if (cajaUser.getText().isEmpty()) {
            cajaUser.setText("Ingrese Usuario");
            cajaUser.setForeground(Color.gray);
            cajaUser.setFont(new Font("Sitka Text", Font.PLAIN, 10));
        }
    }//GEN-LAST:event_cajaUserFocusLost

    private void lExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lExitMouseClicked

    private void icVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icVerMouseClicked
        // TODO add your handling code here:
        if(this.x==0){
            cajaPassword.setEchoChar((char) 0);
            x=1;
            ImageIcon icono2 = new ImageIcon(getClass().getResource("/picture/ocultar.png"));
            Image imagen2 = icono2.getImage().getScaledInstance(
                icVer.getWidth(),
                icVer.getHeight(),
                Image.SCALE_SMOOTH
            );
            icVer.setIcon(new ImageIcon(imagen2));
        }else{
            ImageIcon icono2 = new ImageIcon(getClass().getResource("/picture/ver.png"));
            Image imagen2 = icono2.getImage().getScaledInstance(
                icVer.getWidth(),
                icVer.getHeight(),
                Image.SCALE_SMOOTH
            );
            icVer.setIcon(new ImageIcon(imagen2));
            cajaPassword.setEchoChar('●');
            this.x=0;
        }
    }//GEN-LAST:event_icVerMouseClicked

    private void lAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAtrasMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        inicio vista = new inicio();
        vista.setVisible(true);
    }//GEN-LAST:event_lAtrasMouseClicked
 
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaUser;
    private javax.swing.JLabel icVer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lAtras;
    private javax.swing.JLabel lExit;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
